### ISSUE TITLE
iOS build is failing

### ISSUE THREAD

**Issue by sinodko** [mockingbot/react-native-zip-archive#146]
Hello I'm getting this error while trying to build an ios app.

```
** BUILD FAILED **


The following commands produced analyzer issues:
        Analyze /PATH_TO_PROJECT/node_modules/react-native/ReactCommon/jsi/jsi.cpp normal x86_64
        Analyze /PATH_TO_PROJECT/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
        Analyze /PATH_TO_PROJECT/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(3 commands with analyzer issues)

The following build commands failed:
        CompileC /PATH_TO_PROJECT/ios/build/eccNativeApp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNZipArchive.build/Objects-normal/x86_64/mz_crypt_apple.o /PATH_TO_PROJECT/node_modules/react-native-zip-archive/ios/SSZipArchive/minizip/mz_crypt_apple.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Versions:
```
"react": "16.8.3",
"react-native": "0.59.9",
"react-native-zip-archive": "4.1.0",
```

The package is installed via cocoapods using following line:

```pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'```

Also enclosing screenshot from xCode build

<img width="271" alt="Screenshot 2019-06-26 at 12 14 59" src="https://user-images.githubusercontent.com/33039909/60171987-0a384480-980c-11e9-8f5d-8f96a4fa2602.png">

Does anybody know what can I do?

//EDIT

I've already re-linked the package after upgrade but it is not working anyway

**Comment by sinodko** [comment]
Also enclosing screenshot from xCode build

<img width="271" alt="Screenshot 2019-06-26 at 12 14 59" src="https://user-images.githubusercontent.com/33039909/60171987-0a384480-980c-11e9-8f5d-8f96a4fa2602.png">

**Comment by sinodko** [comment]
Enclosing another images from xCode build process...

<img width="1317" alt="Screenshot 2019-06-26 at 12 30 23" src="https://user-images.githubusercontent.com/33039909/60173062-3fde2d00-980e-11e9-93b5-3f1a563cc4ab.png">

<img width="1317" alt="Screenshot 2019-06-26 at 12 30 33" src="https://user-images.githubusercontent.com/33039909/60173064-4076c380-980e-11e9-891e-5ee72c3a2d7c.png">

**Comment by SDxBacon** [comment]
It looks like the CMSEncoder.h and CMSDecoder.h are missing in Security.framework.

**Comment by sinodko** [comment]
Hello SDxBacon. How to do with it? How can i solve it please?

**Comment by plrthink** [comment]
Yes, you should add Security.framework to your targets as described in the release note https://github.com/mockingbot/react-native-zip-archive/releases/tag/4.1.0.

Hope this tutorial http://docs.onemobilesdk.aol.com/ios-ad-sdk/adding-frameworks-xcode.html would help you out.

Also, we should fix it in the podspec which would let the cocoapod do it for you. Would include in the next release.

**Comment by SDxBacon** [comment]
@sinodko I just ran into the same problem like you before I get out off my office. I don't know how to fix it yet :(

@plrthink I do link iOS SDK 12.1 Security.framework into my Expo detached project, but I got the same problem with sinodko. I try to take a look at Security.framework that be linked into my project with XCode. I can't find 
Security/CMSEncoder.h and Security/CMSDecoder.h. Any idea how to fix it?

Thanks

**Comment by sinodko** [comment]
@plrthink I've tried add Security.framework manually but problem still persists :(

**Comment by SDxBacon** [comment]
I find a workaround to solve errors while building , but I got no time to test it on real iPhone device. Followings are what I have tried, @sinodko could you please take some time to give it a try and share the result? It will be very grateful :)

My Xcode shows that the error `Implicit declaration of function {functionName } is invalid in C99` on funcitons like `CMSEncodeContent`, `CMSDecoderCreate`... I guess it is because that these functions are called before they been declared. 

That's really weird. I do linked `Security.framework`, `libz`, `libiconv` as README said, but errors still persists. Then, I take a look at `Security.framework/Headers/Security.h` in iOS SDK 12.1 and 12.2. The `CMSDecoder.h` and `CMSEncoder.h` will be included only when `SEC_OS_OSX_INCLUDES` is defined. In other words, those headers will be included if your project is build for macOS. It might be the reason why I can't find `CMSDecoder.h` and `CMSEncoder.h` inside iPhone SDK directory but I can see them in macOS SDK.

I can't figure out how to use macOS SDK on an iOS project. Thus, I define `MZ_ZEIP_NO_SIGNING` in `mz.h` like:
```c
#defined MZ_ZIP_NO_SIGNING    1
```
So the compiler will ignore `mz_crypt_sign` and `mz_crypt_sign_verify` with my project been built successfully. I am not sure ignoring those two functions will be a good idea or not. I just downloaded this package yesterday and havn't tried it yet.

@plrthink Did I miss anything before building the project.

Thanks

**Comment by sinodko** [comment]
I was able to build & run the app within xCode but `react-native run-ios` is still yelling the same error... Anyways, when I run the app from xCode I'm unable to unzip files :/ 

```
Error: unable to unzip
    at createErrorFromErrorData (a727057d-614b-41bf-8516-d710f484c4c1:11296)
    at a727057d-614b-41bf-8516-d710f484c4c1:11247
    at MessageQueue.__invokeCallback (a727057d-614b-41bf-8516-d710f484c4c1:11766)
    at a727057d-614b-41bf-8516-d710f484c4c1:11491
    at MessageQueue.__guard (a727057d-614b-41bf-8516-d710f484c4c1:11665)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (a727057d-614b-41bf-8516-d710f484c4c1:11490)
    at e (RNDebuggerWorker.js:1)
/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-cor…:3 
```

this is a log from debugging console

**Comment by SDxBacon** [comment]
Hummm...  so, it looks like the `mz_crypt_sign` and `mz_crypt_sign_verify` are both important to unzip archive. I do not have too many experience on developing ios application, but I will keep trying. Hopes we can conquer in the near future :'(

**Comment by SDxBacon** [comment]
Hi @sinodko,

I am facing the same error `Error: unable to unzip` like you when I start a expo project to test this library. Then I spent couple hours to trace the error, I think I have located where the problem is. 

Everytime I called `unzip` method I got error value `-102` returned and `-102` means `MZ_PARAM_ERROR` which been defined in `minizip/mz.h`. Then, I focus on tracking which step re-assign `error` variable with value `MZ_PARAM_ERROR`, and `minizip/mz_zip.c/mz_zip_entry_open_int` [line 1746](https://github.com/mockingbot/react-native-zip-archive/blob/master/ios/SSZipArchive/minizip/mz_zip.c#L1746) is what I got:

```c
static int32_t mz_zip_entry_open_int(void *handle, uint8_t raw, int16_t compress_level, const char *password)
{
    // ...

    if (err == MZ_OK)
    {
        if (zip->entry_raw || zip->file_info.compression_method == MZ_COMPRESS_METHOD_STORE)
            mz_stream_raw_create(&zip->compress_stream);
#if defined(HAVE_ZLIB) || defined(HAVE_LIBCOMP)
        else if (zip->file_info.compression_method == MZ_COMPRESS_METHOD_DEFLATE)
            mz_stream_zlib_create(&zip->compress_stream);
#endif
#ifdef HAVE_BZIP2
        else if (zip->file_info.compression_method == MZ_COMPRESS_METHOD_BZIP2)
            mz_stream_bzip_create(&zip->compress_stream);
#endif
#ifdef HAVE_LZMA
        else if (zip->file_info.compression_method == MZ_COMPRESS_METHOD_LZMA)
            mz_stream_lzma_create(&zip->compress_stream);
#endif
        else
            err = MZ_PARAM_ERROR;   // this line is executed every single time.
    }
    // ...
}
```
Thus, I try to find out what `zip->file_info.compression_method` value is, and I got value `8` where `MZ_COMPRESS_METHOD_DEFLATE` is also defined as `8` in `minizip/mz.h` as well. It means that `HAVE_ZLIB` is not defined and [line 1735](https://github.com/mockingbot/react-native-zip-archive/blob/master/ios/SSZipArchive/minizip/mz_zip.c#L1735) will be ignored by compiler.

Hummm... that's weird. I do link `libz`, `libiconv` and `Security.framework` as @plrthink said. Did I link `libz` in the wrong way?
![影像 2019-6-28 下午2 03](https://user-images.githubusercontent.com/10906745/60322466-20800500-99b2-11e9-9281-3a1c3a615e39.jpg)

**My enviroment:**
EXPO: SDK 33
React Native: 0.59.8
react-native-zip-archive: 4.1.0

Thanks!

**Comment by plrthink** [comment]
Could you please provide a minimum project to reproduce this error? Actually, I haven't tested this with either expo or cocoapods setup, so a sample app would help to get into the context to fix this.

**Comment by sinodko** [comment]
@plrthink I can confirm that unzipping is working with 4.1.1 release :) Thank you so much! And feel free to close this issue :) Thank you so much!

**Comment by plrthink** [comment]
@sinodko sounds cool! thanks to the PR https://github.com/mockingbot/react-native-zip-archive/pull/147 opened by @mars-lan which solves the issue with cocoapods.

But it seems like @SDxBacon is using ejected expo project, so it may the issue still happens on his side. I would like to let it open until it fixed for him.

@SDxBacon Could you please try the version v4.1.1? Not sure how expo works with native modules. I would check it very soon.

**Comment by SDxBacon** [comment]
Hi @plrthink, I just finished my test with v4.1.1 couple minutes ago, and unzipping is working well now!

As SSZipArchive is marked as dependency in cocoapods, unzipping is working even `libz`, `libiconv`, `Security.framework` is not linked in my ejected expo project. Bravo @mars-lan!

I am pretty sure that this issue can be closed now. @plrthink, thank you so much!
